<?php

namespace ContainerCt77TBW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6YuPC2MService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6YuPC2M' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6YuPC2M'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'shippingDetail' => ['privates', '.errored..service_locator.6YuPC2M.App\\Entity\\ShippingDetails', NULL, 'Cannot autowire service ".service_locator.6YuPC2M": it needs an instance of "App\\Entity\\ShippingDetails" but this type has been excluded in "config/services.yaml".'],
        ], [
            'shippingDetail' => 'App\\Entity\\ShippingDetails',
        ]);
    }
}
