<?php

namespace ContainerCt77TBW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L5g2zuHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.l5g2zuH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.l5g2zuH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'makeComment' => ['privates', '.errored..service_locator.l5g2zuH.App\\Entity\\MakeComment', NULL, 'Cannot autowire service ".service_locator.l5g2zuH": it needs an instance of "App\\Entity\\MakeComment" but this type has been excluded in "config/services.yaml".'],
            'makeCommentRepository' => ['privates', 'App\\Repository\\MakeCommentRepository', 'getMakeCommentRepositoryService', true],
        ], [
            'makeComment' => 'App\\Entity\\MakeComment',
            'makeCommentRepository' => 'App\\Repository\\MakeCommentRepository',
        ]);
    }
}
