<?php

namespace ContainerCt77TBW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GfV04Z1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GfV04Z1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GfV04Z1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'makeCommentRepository' => ['privates', 'App\\Repository\\MakeCommentRepository', 'getMakeCommentRepositoryService', true],
        ], [
            'makeCommentRepository' => 'App\\Repository\\MakeCommentRepository',
        ]);
    }
}
