<?php

namespace ContainerCt77TBW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KwGATQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KwGA_tQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KwGA_tQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'shippingDetailsRepository' => ['privates', 'App\\Repository\\ShippingDetailsRepository', 'getShippingDetailsRepositoryService', true],
        ], [
            'shippingDetailsRepository' => 'App\\Repository\\ShippingDetailsRepository',
        ]);
    }
}
