<?php

namespace ContainerCt77TBW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShippingDetailsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6YuPC2M.App\Entity\ShippingDetails' shared service.
     *
     * @return \App\Entity\ShippingDetails
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6YuPC2M": it needs an instance of "App\\Entity\\ShippingDetails" but this type has been excluded in "config/services.yaml".');
    }
}
