<?php

namespace ContainerXMfemJc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ThE5AkKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ThE5AkK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ThE5AkK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\MakeCommentController::delete' => ['privates', '.service_locator.l5g2zuH', 'get_ServiceLocator_L5g2zuHService', true],
            'App\\Controller\\MakeCommentController::edit' => ['privates', '.service_locator.l5g2zuH', 'get_ServiceLocator_L5g2zuHService', true],
            'App\\Controller\\MakeCommentController::index' => ['privates', '.service_locator.GfV04Z1', 'get_ServiceLocator_GfV04Z1Service', true],
            'App\\Controller\\MakeCommentController::new' => ['privates', '.service_locator.GfV04Z1', 'get_ServiceLocator_GfV04Z1Service', true],
            'App\\Controller\\MakeCommentController::show' => ['privates', '.service_locator.NW94rP1', 'get_ServiceLocator_NW94rP1Service', true],
            'App\\Controller\\ProductController::delete' => ['privates', '.service_locator.DG8Afcf', 'get_ServiceLocator_DG8AfcfService', true],
            'App\\Controller\\ProductController::edit' => ['privates', '.service_locator.DG8Afcf', 'get_ServiceLocator_DG8AfcfService', true],
            'App\\Controller\\ProductController::index' => ['privates', '.service_locator.DZowHzb', 'get_ServiceLocator_DZowHzbService', true],
            'App\\Controller\\ProductController::new' => ['privates', '.service_locator.DZowHzb', 'get_ServiceLocator_DZowHzbService', true],
            'App\\Controller\\ProductController::show' => ['privates', '.service_locator.TxLdxz8', 'get_ServiceLocator_TxLdxz8Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\ShippingDetailsController::delete' => ['privates', '.service_locator.dL8K7YN', 'get_ServiceLocator_DL8K7YNService', true],
            'App\\Controller\\ShippingDetailsController::edit' => ['privates', '.service_locator.dL8K7YN', 'get_ServiceLocator_DL8K7YNService', true],
            'App\\Controller\\ShippingDetailsController::index' => ['privates', '.service_locator.KwGA_tQ', 'get_ServiceLocator_KwGATQService', true],
            'App\\Controller\\ShippingDetailsController::new' => ['privates', '.service_locator.KwGA_tQ', 'get_ServiceLocator_KwGATQService', true],
            'App\\Controller\\ShippingDetailsController::show' => ['privates', '.service_locator.6YuPC2M', 'get_ServiceLocator_6YuPC2MService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.yVvQ1jo', 'get_ServiceLocator_YVvQ1joService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.yVvQ1jo', 'get_ServiceLocator_YVvQ1joService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\MakeCommentController:delete' => ['privates', '.service_locator.l5g2zuH', 'get_ServiceLocator_L5g2zuHService', true],
            'App\\Controller\\MakeCommentController:edit' => ['privates', '.service_locator.l5g2zuH', 'get_ServiceLocator_L5g2zuHService', true],
            'App\\Controller\\MakeCommentController:index' => ['privates', '.service_locator.GfV04Z1', 'get_ServiceLocator_GfV04Z1Service', true],
            'App\\Controller\\MakeCommentController:new' => ['privates', '.service_locator.GfV04Z1', 'get_ServiceLocator_GfV04Z1Service', true],
            'App\\Controller\\MakeCommentController:show' => ['privates', '.service_locator.NW94rP1', 'get_ServiceLocator_NW94rP1Service', true],
            'App\\Controller\\ProductController:delete' => ['privates', '.service_locator.DG8Afcf', 'get_ServiceLocator_DG8AfcfService', true],
            'App\\Controller\\ProductController:edit' => ['privates', '.service_locator.DG8Afcf', 'get_ServiceLocator_DG8AfcfService', true],
            'App\\Controller\\ProductController:index' => ['privates', '.service_locator.DZowHzb', 'get_ServiceLocator_DZowHzbService', true],
            'App\\Controller\\ProductController:new' => ['privates', '.service_locator.DZowHzb', 'get_ServiceLocator_DZowHzbService', true],
            'App\\Controller\\ProductController:show' => ['privates', '.service_locator.TxLdxz8', 'get_ServiceLocator_TxLdxz8Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\ShippingDetailsController:delete' => ['privates', '.service_locator.dL8K7YN', 'get_ServiceLocator_DL8K7YNService', true],
            'App\\Controller\\ShippingDetailsController:edit' => ['privates', '.service_locator.dL8K7YN', 'get_ServiceLocator_DL8K7YNService', true],
            'App\\Controller\\ShippingDetailsController:index' => ['privates', '.service_locator.KwGA_tQ', 'get_ServiceLocator_KwGATQService', true],
            'App\\Controller\\ShippingDetailsController:new' => ['privates', '.service_locator.KwGA_tQ', 'get_ServiceLocator_KwGATQService', true],
            'App\\Controller\\ShippingDetailsController:show' => ['privates', '.service_locator.6YuPC2M', 'get_ServiceLocator_6YuPC2MService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.yVvQ1jo', 'get_ServiceLocator_YVvQ1joService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.yVvQ1jo', 'get_ServiceLocator_YVvQ1joService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\MakeCommentController::delete' => '?',
            'App\\Controller\\MakeCommentController::edit' => '?',
            'App\\Controller\\MakeCommentController::index' => '?',
            'App\\Controller\\MakeCommentController::new' => '?',
            'App\\Controller\\MakeCommentController::show' => '?',
            'App\\Controller\\ProductController::delete' => '?',
            'App\\Controller\\ProductController::edit' => '?',
            'App\\Controller\\ProductController::index' => '?',
            'App\\Controller\\ProductController::new' => '?',
            'App\\Controller\\ProductController::show' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\ShippingDetailsController::delete' => '?',
            'App\\Controller\\ShippingDetailsController::edit' => '?',
            'App\\Controller\\ShippingDetailsController::index' => '?',
            'App\\Controller\\ShippingDetailsController::new' => '?',
            'App\\Controller\\ShippingDetailsController::show' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\MakeCommentController:delete' => '?',
            'App\\Controller\\MakeCommentController:edit' => '?',
            'App\\Controller\\MakeCommentController:index' => '?',
            'App\\Controller\\MakeCommentController:new' => '?',
            'App\\Controller\\MakeCommentController:show' => '?',
            'App\\Controller\\ProductController:delete' => '?',
            'App\\Controller\\ProductController:edit' => '?',
            'App\\Controller\\ProductController:index' => '?',
            'App\\Controller\\ProductController:new' => '?',
            'App\\Controller\\ProductController:show' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\ShippingDetailsController:delete' => '?',
            'App\\Controller\\ShippingDetailsController:edit' => '?',
            'App\\Controller\\ShippingDetailsController:index' => '?',
            'App\\Controller\\ShippingDetailsController:new' => '?',
            'App\\Controller\\ShippingDetailsController:show' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
