<?php

namespace ContainerXMfemJc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DL8K7YNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dL8K7YN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dL8K7YN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'shippingDetail' => ['privates', '.errored..service_locator.dL8K7YN.App\\Entity\\ShippingDetails', NULL, 'Cannot autowire service ".service_locator.dL8K7YN": it needs an instance of "App\\Entity\\ShippingDetails" but this type has been excluded in "config/services.yaml".'],
            'shippingDetailsRepository' => ['privates', 'App\\Repository\\ShippingDetailsRepository', 'getShippingDetailsRepositoryService', true],
        ], [
            'shippingDetail' => 'App\\Entity\\ShippingDetails',
            'shippingDetailsRepository' => 'App\\Repository\\ShippingDetailsRepository',
        ]);
    }
}
