<?php

namespace ContainerXMfemJc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMakeComment2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.l5g2zuH.App\Entity\MakeComment' shared service.
     *
     * @return \App\Entity\MakeComment
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.l5g2zuH": it needs an instance of "App\\Entity\\MakeComment" but this type has been excluded in "config/services.yaml".');
    }
}
