<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXMfemJc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXMfemJc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXMfemJc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXMfemJc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXMfemJc\App_KernelDevDebugContainer([
    'container.build_hash' => 'XMfemJc',
    'container.build_id' => 'b8800e8d',
    'container.build_time' => 1684279429,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXMfemJc');
